server:
  port: 9900
spring:
  application:
    name: cloud-turbine #为你的应用起个名字，该名字将注册到eureka注册中心
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    registerWithEureka: false #false:不作为一个客户端注册到注册中心   
    fetchRegistry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #去哪里注册，eureka服务地址

turbine:
  appConfig: cloud-client-producer
  aggregator:
    clusterConfig: MAIN
  clusterNameExpression: metadata['cluster']      