server:
  port: 8800
spring:
  application:
    name: cloud-client-producer #为你的应用起个名字，该名字将注册到eureka注册中心
  zipkin:
    base-url:http://localhost:9901  
    enabled:true
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    metadata-map:
      cluster: MAIN
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #去哪里注册，eureka服务地址
      