server:
  port: 9411
spring:
  application:
    name: zipkin-server #为你的应用起个名字，该名字将注册到eureka注册中
  #rabbitmq:
    #host: ${RABBIT_HOST:localhost}
  #datasource:
    #schema: classpath:/mysql.sql
    #url: jdbc:mysql://localhost:3306/zipkinserver?useUnicode=true&amp;characterEncoding=UTF-8
    #username: root
    #password: 123456
    #initialize: true
    #continueOnError: true
  #sleuth:
    #enabled: false
#zipkin:
  #storage:
    #type: mysql        
eureka:
  client:
    registerWithEureka: false #false:不作为一个客户端注册到注册中心   
    fetchRegistry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #去哪里注册，eureka服务地址
      